
== General Requirements

[[sec_4.1]]
=== Consensus Process

The SDO shall provide a process to achieve consensus in the development
of its standards under SCC's accreditation.

NOTE: Consensus does not imply unanimity.

NOTE: Sustained opposition is not intended to provide a  "`veto`" to any
one stakeholder.

[[sec_4.2]]
=== Identification of Canadian Interest & Need

The SDO shall consider the following sub-clauses at the beginning
of the development process of a standard, prior to the publication
of the Notice of Intent (NOI) for a new standard or new edition.

NOTE: No guidance.

[[sec_4.2.1]]
==== Strategic Need

Identify the strategic need of key stakeholders and confirmation expressing
the need (e.g. Authority Having Jurisdiction [AHJ], industry, government,
consumers).

This includes:

. strategic need of key stakeholder (e.g. legislator, industry, government,
consumers);
. type of standard (international, regional, domestic standards and
harmonization need);
. up-to-date vs outdated standard to ensure latest innovative/technology/safety
features available for businesses;
. intended to support national/regional/international certification
programs;
. stakeholder intention to transition to different standard;
. type of maintenance (periodic, continuous, stabilized, best before
date); and
. use of  "`CAN`" descriptor.

NOTE: No guidance.

[[sec_4.2.2]]
==== Availability in Both Official Languages

The SDO shall publish the standard in both of Canada's official languages.
The following criteria shall be applied to determine when a bilingual
standard is not required:

. no stakeholders' need;
. no user base need;
. no AHJ need; and
. no health and safety related needs.

The SDO shall apply the above criteria (a-d) at any point, when the
need is identified.

For ISO/IEC adoptions where a Canadian need has been identified for
bilingual publications, SDOs shall use the available ISO/IEC translations.
Where no French translation is available, SDOs shall conduct a national
translation and publish the ISO/IEC adopted NSC, with the French translation
as non official, in alignment with ISO/IEC language policy.

NOTE: When a stakeholder does not require a bilingual standard and no
French translation of ISO/IEC is available the English-only adoption
is permitted.

[[sec_4.2.3]]
==== Geographical Representation

The SDO's technical committee shall include Canadian representation
appropriate to the subject area covered by the standard.

NOTE: Geographic representation may consider factors such as industry
location (e.g. petroleum in petroleum producing provinces), reference
in regulation (if a regulation exists in a province), commodity characteristics
and social impact (e.g. heating oil for northern climates).

[[sec_4.3]]
=== Avoiding Duplication

SDOs shall make every effort to address the need of the Canadian stakeholder(s)
and to not duplicate or overlap with the work of other SCC-accredited
SDOs, or relevant international or regional SDOs.

NOTE: No guidance.

[[sec_4.3.1]]
==== Identification of Duplication

The SDO shall monitor the Centralized Notification System (CNS) platform.
When a duplication complaint is raised, the SDO shall use the Duplication
Resolution Mechanism (DRM), as described in the CSD - POV.

NOTE: No guidance.

[[sec_4.3.2]]
==== Action Plan - Decision Impact

The SDO shall comply with the Action Plan resulting from the DRM process,
defined under the CSD-POV.

NOTE: No guidance.

[[sec_4.4]]
=== Work Program

The SDO shall provide the Work Program content to SCC to be published
on SCC's CNS platform.

NOTE: No guidance.

[[sec_4.4.1]]
==== Frequency of Publication

The SDO shall publish their Work Program at least once every six months.

NOTE: No guidance.

[[sec_4.4.2]]
==== Content

The Work Program shall include:

. the standards the SDO is currently preparing;
. the standards the SDO has published in the preceding period;
. the classification relevant to the subject matter of the standard
using the International Classification for Standards,  "`ICS`" code(s);
. the development-stage code and start date, based on the ISO International
harmonized stage codes;
. the public review comment period start and end dates; and
. references to any International Standards taken as a basis.

The notice shall contain:

. the name and address of the SDO;
. the name and issue of the publication in which the Work Program
is published;
. the period to which the Work Program applies;
. the price of the publication (if any); and
. how and where the Work Program can be obtained.

NOTE: The Work Program content may be submitted in either of Canada's
official languages.

NOTE: The targeted publication date of standards should be included in the
Work Program content.

[[sec_4.4.3]]
==== Availability

The SDO shall make the Work Program publicly available. The SDO shall
promptly provide or arrange to provide a copy of its most recent Work
Program upon request. Any fees charged for this service shall, apart
from the real costs of delivery, be the same for foreign and domestic
parties.

NOTE: No guidance.

[[sec_4.5]]
=== International/Regional/National Harmonization

When international/regional standards exist or their completion is
imminent, they, or their relevant parts, shall be used as the basis
for corresponding standards developed by SDOs. The SDO shall identify
and create a list of the standards considered.

NOTE: Except, if the international/regional standard, or relevant parts,
are determined to be ineffective or inappropriate; this may include
an insufficient level of protection, fundamental climatic, geographical
factors or fundamental technological problems.

[[sec_4.6]]
=== Standards Harmonization With International Community -- SDO Participation

The SDO shall give priority to participate, within the limits of its
resources, in the preparation of international and regional standards
which it expects to develop or adopt.

NOTE: Harmonization of ISO/IEC SCC Mirror Committees with the technical
committee of an SDO is done in accordance with SCC's policy on harmonization.

[[sec_4.7]]
=== National Adoption of International/Regional Standards and Other Deliverables

In addition to the R&G - SDO Accreditation, the SDO shall comply with
the _Requirements & Guidance -- National Adoptions of International/Regional
Standards and Other Deliverables_ when adopting an ISO, IEC, or regional
standard as a NSC.

NOTE: No guidance.

[[sec_4.8]]
=== Performance Based Standards

The requirements of standards shall be expressed in terms of performance
rather than design or descriptive characteristics, whenever possible.

NOTE: When an SDO determines that it is not possible to express the requirements
in terms of performance, a rationale should be identified.

[[sec_4.9]]
=== Trade

The SDO shall ensure that standards developed do not create unnecessary
obstacles to international and/or inter-provincial trade.

The SDO shall take action to resolve identified impediments or inhibitions
to trade.

NOTE: Standards should be developed to meet the needs of the marketplace
and should contribute to advancing trade in the broadest possible
geographical and economic contexts.

NOTE: Standards should not include requirements for third party certification
or requirements from authorities having jurisdiction. This type of
content may be provided as informative material.

[[sec_4.10]]
=== Place of Origin

The SDO shall ensure that standards are not developed to discriminate
among products on the basis of the place of origin.

The SDO shall take action to resolve identified instances of unjustified
discrimination, and remove the potential for future instances.

NOTE: In drafting the requirements of the standard, the SDO should safeguard
that the source of the materials for the product of the standard is
not prescriptive as to specify one location where they may be obtained.

[[sec_4.11]]
=== Price Fixing

The SDO shall ensure that standards are not developed as a means to
fix prices, exclude competition, or otherwise inhibit commerce beyond
what is necessary to meet requirements of relevant technical regulations,
or other legitimate sectoral or local requirements for compatibility,
environmental protection, health and safety.

NOTE: No guidance.

[[sec_4.12]]
=== Protection Against Misleading Standards

The SDO shall ensure that the process to develop standards minimizes
the possibility that the standards may be used to mislead consumers
and other users of a product, process or service addressed by the
standard.

The SDO shall take action to resolve identified instances of standards
being used to mislead.

NOTE: In drafting the requirements of the standard, the SDO should safeguard
that the end product addresses the intended purpose. For example,
that it contains current and accurate technical information.

[[sec_4.13]]
=== Patents

The SDO shall have a patent policy that restricts the inclusion of
patented items in a standard, unless justifiable for technical reasons,
and the holder of the rights agrees to negotiate licenses.

NOTE: For additional guidance refer to the ISO/IEC Directives, Part 1,
-- _Consolidated ISO Supplement -- Procedures specific to ISO, 2019_,
clause 2.14 and Annex I, Reference to patented items.

[[sec_4.14]]
=== References to Certification or Administrative Requirements

No requirement.

NOTE: Administrative requirements relating to conformity assessment,
marks of conformity, or other non-technical issues should be presented
separately from technical requirements.

[[sec_4.15]]
=== Standards for Conformity Assessment

Standards intended for conformity assessment shall contain a clear
statement to that effect in the introductory pages.

Standards requirements shall be based on requirements that are stated,
to the extent possible, in measurable terms, and the rationale for
such requirements shall be provided.

NOTE: In this context conformity assessment refers to third party certification.

NOTE: Standards should not include requirements for third party certification
or requirements from authorities having jurisdiction. This type of
content may be provided as informative material.

[[sec_4.16]]
=== Safety Markings

When the technical committee requires the inclusion of safety markings
to address safety issues, the appropriate cautionary text shall be
provided in both of Canada's official languages.

NOTE: A safety marking depicting a graphical symbol without supplementary
text is acceptable, such as the symbols provided in the International
Standards series ISO 3864.

[[sec_4.17]]
=== Conflict of Interest

The SDO shall ensure that technical committee members and SDO staff
involved in standards development have no conflict of interest in
carrying out their roles and responsibilities on the technical committee.

NOTE: No guidance.

[[sec_4.18]]
=== Declaration of Compliance with Accreditation Requirements

The SDO shall include a statement in the introductory pages of a standard
indicating the standard was developed in compliance with SCC's R&Gs
for SDOs.

NOTE: No guidance.

[[sec_4.19]]
=== Provision of Published Standards

Upon publication, the SDO shall submit to SCC electronic copies of
new standards, new editions, revisions, reaffirmations and the underlying
metadata.

NOTE: No guidance.
