
== Requirements & Guidance

.REQUIREMENTS & GUIDANCE
[cols="a,a,a",options="header"]
|===
| Clause | SCC Requirement | SCC Guidance

3+h| 4. General Requirements

| *4.1*
| *Consensus Process*

The SDO shall provide a process to achieve consensus in the development
of its standards under SCC's accreditation.
| Consensus does not imply unanimity.

Sustained opposition is not intended to provide a  "`veto`" to any
one stakeholder.

| *4.2*
| *Identification of Canadian Interest & Need*

The SDO shall consider the following sub- clauses at the beginning
of the development process of a standard, prior to the publication
of the Notice of Intent (NOI) for a new standard or new edition.
| No guidance

| 4.2.1
| [underline]#Strategic Need#

Identify the strategic need of key stakeholders and confirmation expressing
the need (e.g. Authority Having Jurisdiction [AHJ], industry, government,
consumers).

This includes:

. strategic need of key stakeholder (e.g. legislator, industry, government,
consumers);
. type of standard (international, regional, domestic standards and
harmonization need);
. up-to-date vs outdated standard to ensure latest innovative/technology/safety
features available for businesses;
. intended to support national/regional/international certification
programs;
. stakeholder intention to transition to different standard;
. type of maintenance (periodic, continuous, stabilized, best before
date); and
. use of  "`CAN`" descriptor.
| No guidance

| 4.2.2
| [underline]#Availability in Both Official Languages#

The SDO shall publish the standard in both of Canada's official languages.
The following criteria shall be applied to determine when a bilingual
standard is not required:

. no stakeholders' need;
. no user base need;
. no AHJ need; and
. no health and safety related needs.

The SDO shall apply the above criteria (a-d) at any point, when the
need is identified.

For ISO/IEC adoptions where a Canadian need has been identified for
bilingual publications, SDOs shall use the available ISO/IEC translations.
Where no French translation is available, SDOs shall conduct a national
translation and publish the ISO/IEC adopted NSC, with the French translation
as non official, in alignment with ISO/IEC language policy.
| When a stakeholder does not require a bilingual standard and no
French translation of ISO/IEC is available the English-only adoption
is permitted.

| 4.2.3
| [underline]#Geographical Representation#

The SDO's technical committee shall include Canadian representation
appropriate to the subject area covered by the standard.
| Geographic representation may consider factors such as industry
location (e.g. petroleum in petroleum producing provinces), reference
in regulation (if a regulation exists in a province), commodity characteristics
and social impact (e.g. heating oil for northern climates).

| *4.3*
| *Avoiding Duplication*

SDOs shall make every effort to address the need of the Canadian stakeholder(s)
and to not duplicate or overlap with the work of other SCC-accredited
SDOs, or relevant international or regional SDOs.
| No guidance

| 4.3.1
| [underline]#Identification of Duplication#

The SDO shall monitor the Centralized Notification System (CNS) platform.
When a duplication complaint is raised, the SDO shall use the Duplication
Resolution Mechanism (DRM), as described in the CSD - POV.
| No guidance

| 4.3.2
| [underline]#Action Plan - Decision Impact#

The SDO shall comply with the Action Plan resulting from the DRM process,
defined under the CSD-POV.
| No guidance

| *4.4*
| *Work Program*

The SDO shall provide the Work Program content to SCC to be published
on SCC's CNS platform.
| No guidance

| 4.4.1
| [underline]#Frequency of Publication#

The SDO shall publish their Work Program at least once every six months.
| No guidance

| 4.4.2
| [underline]#Content#

The Work Program shall include:

. the standards the SDO is currently preparing;
. the standards the SDO has published in the preceding period;
. the classification relevant to the subject matter of the standard
using the International Classification for Standards,  "`ICS`" code(s);
. the development-stage code and start date, based on the ISO International
harmonized stage codes;
. the public review comment period start and end dates; and
. references to any International Standards taken as a basis.

The notice shall contain:

. the name and address of the SDO;
. the name and issue of the publication in which the Work Program
is published;
. the period to which the Work Program applies;
. the price of the publication (if any); and
. how and where the Work Program can be obtained.
| The Work Program content may be submitted in either of Canada's
official languages.

The targeted publication date of standards should be included in the
Work Program content.

| 4.4.3
| [underline]#Availability#

The SDO shall make the Work Program publicly available. The SDO shall
promptly provide or arrange to provide a copy of its most recent Work
Program upon request. Any fees charged for this service shall, apart
from the real costs of delivery, be the same for foreign and domestic
parties.
| No guidance

| *4.5*
| *International/Regional/National Harmonization*

When international/regional standards exist or their completion is
imminent, they, or their relevant parts, shall be used as the basis
for corresponding standards developed by SDOs. The SDO shall identify
and create a list of the standards considered.
| Except, if the international/regional standard, or relevant parts,
are determined to be ineffective or inappropriate; this may include
an insufficient level of protection, fundamental climatic, geographical
factors or fundamental technological problems.

| *4.6*
| *Standards Harmonization With International Community -- SDO Participation*

The SDO shall give priority to participate, within the limits of its
resources, in the preparation of international and regional standards
which it expects to develop or adopt.
| Harmonization of ISO/IEC SCC Mirror Committees with the technical
committee of an SDO is done in accordance with SCC's policy on harmonization.

| *4.7*
| *National Adoption of International/Regional Standards and Other
Deliverables*

In addition to the R&G - SDO Accreditation, the SDO shall comply with
the _Requirements & Guidance -- National Adoptions of International/Regional
Standards and Other Deliverables_ when adopting an ISO, IEC, or regional
standard as a NSC.
| No guidance

| *4.8*
| *Performance Based Standards*

The requirements of standards shall be expressed in terms of performance
rather than design or descriptive characteristics, whenever possible.
| When an SDO determines that it is not possible to express the requirements
in terms of performance, a rationale should be identified.

| *4.9*
| *Trade*

The SDO shall ensure that standards developed do not create unnecessary
obstacles to international and/or inter- provincial trade.

The SDO shall take action to resolve identified impediments or inhibitions
to trade.
| Standards should be developed to meet the needs of the marketplace
and should contribute to advancing trade in the broadest possible
geographical and economic contexts.

Standards should not include requirements for third party certification
or requirements from authorities having jurisdiction. This type of
content may be provided as informative material.

| *4.10*
| *Place of Origin*

The SDO shall ensure that standards are not developed to discriminate
among products on the basis of the place of origin.

The SDO shall take action to resolve identified instances of unjustified
discrimination, and remove the potential for future instances.
| In drafting the requirements of the standard, the SDO should safeguard
that the source of the materials for the product of the standard is
not prescriptive as to specify one location where they may be obtained.

| *4.11*
| *Price Fixing*

The SDO shall ensure that standards are not developed as a means to
fix prices, exclude competition, or otherwise inhibit commerce beyond
what is necessary to meet requirements of relevant technical regulations,
or other legitimate sectoral or local requirements for compatibility,
environmental protection, health and safety.
| No guidance

| *4.12*
| *Protection Against Misleading Standards*

The SDO shall ensure that the process to develop standards minimizes
the possibility that the standards may be used to mislead consumers
and other users of a product, process or service addressed by the
standard.

The SDO shall take action to resolve identified instances of standards
being used to mislead.
| In drafting the requirements of the standard, the SDO should safeguard
that the end product addresses the intended purpose. For example,
that it contains current and accurate technical information.

| *4.13*
| *Patents*

The SDO shall have a patent policy that restricts the inclusion of
patented items in a standard, unless justifiable for technical reasons,
and the holder of the rights agrees to negotiate licenses.
| For additional guidance refer to the ISO/IEC Directives, Part 1,
-- _Consolidated ISO Supplement -- Procedures specific to ISO, 2019_,
clause 2.14 and Annex I, Reference to patented items.

| *4.14*
| No requirement

| *References to Certification or Administrative Requirements*

Administrative requirements relating to conformity assessment, marks
of conformity, or other non- technical issues should be presented
separately from technical requirements.

| *4.15*
| *Standards for Conformity Assessment*

Standards intended for conformity assessment shall contain a clear
statement to that effect in the introductory pages.

Standards requirements shall be based on requirements that are stated,
to the extent possible, in measurable terms, and the rationale for
such requirements shall be provided.
| In this context conformity assessment refers to third party certification.

Standards should not include requirements for third party certification
or requirements from authorities having jurisdiction. This type of
content may be provided as informative material.

| *4.16*
| *Safety Markings*

When the technical committee requires the inclusion of safety markings
to address safety issues, the appropriate cautionary text shall be
provided in both of Canada's official languages.
| A safety marking depicting a graphical symbol without supplementary
text is acceptable, such as the symbols provided in the International
Standards series ISO 3864.

| *4.17*
| *Conflict of Interest*

The SDO shall ensure that technical committee members and SDO staff
involved in standards development have no conflict of interest in
carrying out their roles and responsibilities on the technical committee.
| No guidance

| *4.18*
| *Declaration of Compliance with Accreditation Requirements*

The SDO shall include a statement in the introductory pages of a standard
indicating the standard was developed in compliance with SCC's R&Gs
for SDOs.
| No guidance

| *4.19*
| *Provision of Published Standards*

Upon publication, the SDO shall submit to SCC electronic copies of
new standards, new editions, revisions, reaffirmations and the underlying
metadata.
| No guidance

3+h| 5. Structural and Resource Requirements

| *5.1*
| *Canadian Relevance*

The SDO shall be actively developing and maintaining standards, in
a timely manner, and demonstrate a standards interest of relevance
to Canada.

The SDO shall provide the following evidence to demonstrate Canadian
relevance:

. appropriate participation of Canadian experts in technical committees;
and
. facilities in Canada with sufficient resources to meet requirements
relevant to its standards development activities.
| No guidance

| *5.2*
| *Legal Responsibility*

The SDO shall be a legal entity, or a defined part of a legal entity,
such that it can be held legally responsible for all its standards
development activities.
| No guidance

| *5.3*
| *Separation of Management Activities*

The SDO, if corporately linked to a certification body, quality system
registrar or similar activities, shall demonstrate a clear separation
of the management and policy-making functions of such activities from
those of standards development.

The SDO shall demonstrate compliance by reference to their policy,
organizational structure and procedural documents.
| No guidance

| *5.4*
| *Continuity of Operations*

The SDO shall:

. have a structure and available resources providing assurance on
the stability and continuity of its operations;
. have available information on its future plans regarding the development
and maintenance of standards; and
. maintain expertise for the development and the maintenance of standards.
| No guidance

| *5.5*
| *Staff Competence*

The SDO shall have sufficient and competent staff to manage its standardization
program and activities. Staff shall be knowledgeable about standardization,
including related matters of principles, policies and techniques.
| No guidance

| *5.6*
| *Facilities*

The SDO shall have appropriate facilities in Canada with sufficient
resources to meet the requirements relevant to its standards development
activities.
| No guidance

| *5.7*
| *Record Keeping*

The SDO shall prepare and maintain adequate records of its standards
development activities.
| No guidance

3+h| 6. Consensus Requirements

| *6.1*
| *Documented Processes Based on Consensus*

The SDO shall have documented policies and procedures for the development,
publication, distribution, and maintenance of its standards. Upon
request, copies of policies and procedures shall be available to interested
parties in a timely manner.

The SDO shall inform SCC when their policies and procedures have been
changed.
| No guidance

| *6.2*
| *Proposals for Development of Standards*

The SDO shall consider proposals for the development of new or revised
standards following their established procedures and appropriate timelines.
| No guidance

| *6.3*
| *Equal Access and Effective Canadian Participation to the Standards
Development Process by Concerned Interests*

The SDO shall ensure that:

. participation in standards development is accessible to affected
stakeholders; and
. there is appropriate Canadian participation on technical committees.

The SDO shall provide evidence of best efforts to address the challenges
of finding resources for participation.
| No guidance

| *6.4*
| *Balance of Interests*

The SDO shall provide for balanced representation of interest categories
in the development of standards. This representation shall reflect
the Canadian interest.

When consumer or public interest representation would provide the
needed balance of interests, the SDO shall identify and make efforts
to secure support for equal access and effective participation of
such interests.
| The commonly used interest categories may include, but are not limited
to, general interest, producers, regulators and users.

Securing support for consumer or public interest participation does
not require the SDO to provide financial support from their operating
budgets.

| *6.5*
| *Use of ISONET: International harmonized stage codes and International
Classification for Standards*

The SDO shall adhere to the requirements in the latest version of
the International harmonized stage codes, and of the ICS codes.
| For the stage code deliverables see the CSD - POV Annex C.

| *6.6*
| *Notification Requirements*

The SDO shall notify the Canadian public at specific stages in the
development process. These stages shall be completed following their
established procedures and appropriate timelines.
| No guidance

| 6.6.1
| [underline]#Notice of Intent (NOI)#

The SDO shall inform the Canadian public by providing their NOIs to
the CNS platform when it has taken the decision to develop or adopt
a new standard or other deliverable, new edition, revision, amendment,
reaffirmation or withdrawal of an already published standard.

The content of the NOI shall include:

. designation number
. title
. scope
. project need
. contact information of the SDO
. ICS code(s)

The SDO shall issue a new NOI when International harmonized stage
code 10, Proposal stage, has not been met within a maximum timeframe
of 12 months.

The SDO shall update the NOI if there are substantive alterations
to the scope and title of the originally proposed NOI.
| NOIs may be submitted in either of Canada's official languages.

| 6.6.2
| [underline]#Notice of Public Review#

The SDO shall notify the Canadian public of standards available for
public review. The public review shall be a minimum period of 60 calendar
days when a draft agreed by the technical committee is available,
and shall be completed before final approval of the technical committee.

The notice shall include the start and end dates of the review period.

The notice shall indicate how to obtain a copy of the draft standard.
On the request of any interested party the SDO shall promptly provide,
or arrange to provide, a copy of the draft standard in question. Any
fees charged for this service shall, apart from the real cost of delivery,
be the same for foreign and domestic parties.

All comments received, regardless of place of origin, shall be considered
by the technical committee, and responded to if requested. Such responses
shall include reasons for deviations from relevant International Standards,
regional standards, and other deliverables if requested.
| The minimum period of 60 calendar days may be shortened with appropriate
rationale and action to proactively inform affected stakeholders.
Appropriate rationale may involve where urgent problems of safety,
health or environment arise or threaten to arise.

As per clause 4.2.2, the SDO has to provide a copy of the draft standard
in question in either of Canada's official languages, as requested
by the interested party.

| 6.6.2.1
| [underline]#Public Review -- 45 Days#

The SDO shall determine if a 45-day public review period is appropriate
when urgent problems of safety, health or environment arise or threaten
to arise.

The SDO shall proactively notify affected stakeholders.

This notification shall include where the draft standard can be obtained
and the public review period start and end dates.

The draft standard shall be available in an electronic format, deliverable
within one day of a request.
| No guidance

| 6.6.3
| [underline]#Notice of Completion#

The SDO shall notify the Canadian public that a standard has been
completed.

Published standards may be commented on at any time, and such comments
shall be referred to the responsible technical committee for consideration,
as appropriate.
| No guidance

| 6.6.4
| [underline]#Notice of Withdrawal#

The SDO shall notify the Canadian public and SCC when it has decided
to withdraw a standard.
| No guidance

| *6.7*
| *Technical Committee Approval Process*

The approval process shall be based on evidence of consensus reached
by the technical committee.

The approval process shall not be used to block or obstruct the promulgation
of standards.
| No guidance

| 6.7.1
| [underline]#Voting Rules#

. More than 50 % (simple majority) of the members who are eligible
to vote cast affirmative votes; and
. A minimum of 2/3 of the votes cast are affirmative.
| No guidance

| 6.7.2
| [underline]#Negative votes#

The SDO shall address negative votes according to its policies and
procedures. Negative votes without justification, abstentions without
justification, as well as unreturned and blank ballots, shall be considered
not cast.
| In addressing a negative vote, the technical committee should review
the negative vote for technical merit. If accepted, the required adjustment(s)
should be made to the applicable requirement(s). If not accepted,
rationale should be provided. In either case, the comment provider
should be informed of resolution and decision.

| *6.8*
| *Second Level Review*

The SDO's procedures shall have at least one level of procedural review
and approval beyond the final approval by the technical committee.
The SDO shall retain evidence of the approval of the second level
review.
| No guidance

| *6.9*
| *Publication Process*

Standards shall only be published in compliance with SCC's R&Gs for
SDOs. They shall be published promptly, and be made available under
reasonable terms and conditions. Any fees charged for this service
shall, apart from the real costs of delivery, be the same for foreign
and domestic parties.
| No guidance

| *6.10*
| *Maintenance of Standards*

The SDO shall be responsive to stakeholder needs by keeping all standards
current and technically relevant through periodic, continuous or stabilized
maintenance.

The SDO shall establish when it is subject to a technical committee
review.

The SDO shall initiate and complete the technical committee review
of each standard within the established timeline.
| A review may result in a new edition, revision, reaffirmation or
withdrawal of the standard.

| 6.10.1
| [underline]#Periodic Maintenance#

Standards shall be kept current and relevant by technical committee
review of the entire document and the outcome activity completion
(publication or withdrawal) not to exceed five years from the date
of publication.
| No guidance

| 6.10.2
| [underline]#Continuous Maintenance#

When technical change is required, the SDO shall:

. validate technical changes with the technical committee;
. take appropriate action in order to address the issue(s); and
. notify affected stakeholders/public.

In the event that no updates are issued for a period of four years
from the date of publication, action to update (new edition or revision),
reaffirm, or withdraw the standard shall be initiated in accordance
with the SDOs procedures.
| Standards developed in areas related to health and safety should
be kept current under continuous maintenance.

| 6.10.3
| [underline]#Stabilized Maintenance#

A standard under stabilized maintenance shall meet the following:

. addresses mature technology/practices;
. is not health or safety related; and
. is a published standard, reaffirmed at least once.
| No guidance

| *6.11*
| *Maintenance Outcomes*

The outcome of the SDO maintenance shall be one of the following sub-clauses.
| No guidance

| 6.11.1
| [underline]#New Edition#

When the SDO develops a new edition of an existing standard, it shall
comply with SCC's R&Gs for SDOs.
| No guidance

| 6.11.2
| [underline]#Revision#

When the SDO conducts technical changes, it shall comply with the
following:

. Equal Access and Effective Canadian Participation to the Standards
Development Process by Concerned Interests, clause 6.3;
. Balance of Interests, clause 6.4;
. Availability in Both Official Languages, clause 4.2.2;
. Geographical Representation, clause 4.2.3;
. Avoiding Duplication, clause 4.3;
. Notice of Intent, clause 6.6.1;
. Work Program, clause 4.4;
. Technical Committee Approval, clause 6.7;
. Number and Title, clause 7.4;
. Front Cover Page, clause 7.5; and
. Introductory Pages, clause 7.6.
| Note, the term amendment is equivalent to revision.

| 6.11.3
| [unerline]#Reaffirmation#

A reaffirmation shall comply with the following:

. Equal Access and Effective Canadian Participation to the Standards
Development Process by Concerned Interests, clause 6.3;
. Balance of Interests, clause 6.4;
. Availability in Both Official Languages, clause 4.2.2;
. Geographical Representation, clause 4.2.3;
. Avoiding Duplication, clause 4.3;
. Notice of Intent, clause 6.6.1;
. Work Program, clause 4.4;
. Technical Committee Approval, clause 6.7;
. Number and Title, clause 7.4;
. Front Cover Page, clause 7.5; and
. Introductory Pages, clause 7.6.
| Normative content in a standard may include the sections starting
at the scope and ending at the last normative annex.

Informative content includes any other sections, such as introductory
pages.

The SDO may determine how to conduct the update of the document to
be reaffirmed.

| 6.11.4
| [underline]#Withdrawal#

When considering the withdrawal of a standard, the SDO shall consider
the impact on Canadian legislation, in particular where a standard
may be referenced.

If a withdrawn standard is included in the listings of standards for
sale, it shall be clearly identified as withdrawn. If it is sold,
the withdrawn status shall be included on the cover of the standard
itself.

When a standard fails to meet SCC's R&Gs for SDOs, the SDO shall withdraw
the standard.
| The SDO should notify the impacted government department(s) in a
timely manner when a standard referenced in Canadian Legislation is
withdrawn.

| *6.12*
| *International Inquiries on Code of Good Practice*

The SDO shall address, in a timely manner, inquiries and complaints
from another SDO that has accepted the WTO/TBT Annex 3 Code of Good
Practice for the Preparation, Adoption and Application of Standards.
| No guidance

| *6.13*
| *Information Requests*

The SDO shall provide standards development-related information on
request, within the limits of applicable privacy legislation.
| No guidance

| *6.14*
| *Complaints and Appeals Mechanism*

The SDO shall have documented procedures for dealing with complaints
and appeals.

These procedures shall:

. provide impartial treatment;
. deal with complaints and appeals promptly;
. provide accessibility to the process; and
. identify SCC's role in the appeal process.
| Complaints may be either of a technical or procedural nature.

An appeal against the final SDO decision may be escalated by registering
an official complaint following the process described in _SCC's Accreditation
Services -- Accreditation Program Overview_ document.

| *6.15*
| *Notification of Suits or Claims*

The SDO shall promptly notify SCC of any suit or claim made against
the SDO arising from a standard designated as an NSC, and provide
periodic updates to SCC of the status of any such suit or claim.
| No guidance

3+h| 7. Format Requirements

| *7.1*
| *Normative Content*

The normative section of the standard shall include the scope, normative
references, technical requirements, and if applicable, normative annexes,
and terms and definitions. If annexes are included they shall be identified
 "`normative`" or  "`informative`".
| The informative content may include, but is not limited to, foreword,
preface, introduction and informative annexes.

| *7.2*
| *Units of Measurement*

The SDO shall include in the standard the international system of
units (SI), and if applicable, equivalent Imperial/U.S. units or other
units of measurement.

ISO 80000 series of standards shall be used to ensure clear and concise
application of SI units, including conversions to and from other systems
of measurement.

It is the responsibility of the user of the standard to determine
the unit of measurement appropriate for the user's needs.
| Conversions expressed in the standard should be approved by the
technical committee.

When no SI unit equivalent exists, such as trade sizes used in Canada,
the trade size unit may be used.

| *7.3*
| *Date and Time*

All-numeric date and time units shall comply with ISO 8601.
| No guidance

| *7.4*
| *Number and Title*

The SDO shall use the  "`CAN`" descriptor preceding the standard designation,
based on the identified strategic need in clause 4.2.1.
| No guidance

| *7.5*
| *Front Cover Page*

The following items shall be included on the front cover page of the
NSC:

. The bilingual SCC logo, placed with other organizational logos,
if any, or at the bottom of the page; and
. The bilingual National Standard of Canada Symbol (NSC Symbol) placed
with other identifying symbols, if any, or near the top of the page.
| No guidance

| *7.6*
| *Introductory Pages*

The NSC shall have introductory pages with the following content in
the language(s) appropriate to the standard:

. the established timeline for review of the standard;
. SCC foreword (CSD - POV, Annex A);
. statement indicating the standard was developed in compliance with
SCC's R&Gs for SDOs;
. the names of the technical committee members or the number of technical
committee members representing the interest categories described in
the R&G --SDO Accreditation, clause 6.4;
. statement of availability of the NSC, English text in the French
version, French text in the English version (CSD - POV, Annex B);
. statement indicating it is the responsibility of the user of the
standard to judge the suitability of the NSC for the user's purpose;
and
. ICS code(s).
| No guidance

3+h| 8. Maintenance of Accreditation

| *8.1*
| *Maintenance of Accreditation*

In order to maintain accreditation by SCC, an SDO shall continue to
maintain procedures complying with the Requirements & Guidance for
SDOs for the publication and withdrawal of standards contained herein.

If an SDO does not maintain one or more approved NSCs within the accreditation
cycle, the SDO shall submit written justification from the head of
the SDO at the reaccreditation as to why they have not submitted any
NSCs to SCC for approval and why their accreditation remains relevant.
| If written justification is not provided or is otherwise unsatisfactory,
the Accreditation Services Branch may suspend or withdraw the accreditation.

| *8.2*
| *Assessments*

SCC's Accreditation Services Branch shall arrange for assessments
of accredited SDOs at selected intervals or due to special circumstances
to confirm adherence to the Requirements & Guidance for SDOs and to
confirm that the procedures and practices of the accredited SDO continue
to be consistent with those which formed the basis for accreditation.
| No guidance

| *8.3*
| *SCC Requirements Updates*

SDOs shall submit to a regular assessment in accordance with the Accreditation
Policy and SDO Accreditation Agreement. When SCC issues revised or
additional Requirements & Guidance for SDOs, the accredited SDO shall
comply with them within a reasonable time period designated by the
SCC's Accreditation Services Branch in order to maintain accreditation.
| No guidance

3+h| 9. Self-Declaration

| *9.1*
| *Eligibility for Self-Declaration Status*

Before an SCC-accredited SDO can be considered for self-declaration
status, the organization shall:

. Complete an application for self- declaration and submit it to SCC
with associated fee;
. Have participated in accreditation assessments for a minimum of
one accreditation cycle (3 years) before applying; and
. The SDO has been assessed within the last 12 months.
| Self-declaration status is voluntary and dependent on an SDO achieving
the criteria outlined in clause 9.2.

| *9.2*
| *Criteria for Approval of SDO Self- Declaration Status*

The following shall be satisfied by the SDO:
| No guidance

| 9.2.1
| SCC has approved at least five distinct standards as NSCs.
| No guidance

| 9.2.2
| The NSCs shall be representative of the SDOs scope of work.
| The five distinct standards should be representative of the technical
work areas where the SDO normally conducts its standards development.

| 9.2.3
| No standard submitted by the SDO during the three year period was
denied the NSC designation by SCC, due to a failure to comply with
the Requirements & Guidance for SDOs.
| No guidance

| 9.2.4
| The SDO is not in arrears with respect to any fees invoiced.
| No guidance

| 9.2.5
| The SDO does not have any open non- conformities from the last assessment
activity.
| No guidance

| 9.2.6
| The SDO does not have any open complaint (whether expressed as a
complaint or appeal) against any NSC.
| No guidance

| *9.3*
| *Maintenance of Self-Declaration Status*
| No guidance

| 9.3.1
| [underline]#Self- Declaration Agreement#

Upon decision to grant self-declaration status, the SDO shall enter
into a written agreement with SCC, which shall include commitments
by the SDO to meet the requirements listed in the sub-clause below:

. The agreement shall be for a term aligned with the accreditation
cycle; and
. Any additional terms included in the agreement may be modified as
circumstances require with prior approval of SCC and the SDO (as long
as such additional term(s) do not conflict with any of SCC's existing
policies and procedures).
| No guidance

| *9.4*
| *Suspension of Self-Declaration Status*
| No guidance

| 9.4.1
| The SDO shall immediately cease to apply the NSC designation to
any standard without obtaining SCC approval after the SDO has been
notified by SCC that its self- declaration status has been suspended
and/or withdrawn.
| No guidance
|===
