
== Structural and Resource Requirements

[[sec_5.1]]
=== Canadian Relevance

The SDO shall be actively developing and maintaining standards, in
a timely manner, and demonstrate a standards interest of relevance
to Canada.

The SDO shall provide the following evidence to demonstrate Canadian
relevance:

. appropriate participation of Canadian experts in technical committees;
and
. facilities in Canada with sufficient resources to meet requirements
relevant to its standards development activities.

NOTE: No guidance.

[[sec_5.2]]
=== Legal Responsibility

The SDO shall be a legal entity, or a defined part of a legal entity,
such that it can be held legally responsible for all its standards
development activities.

NOTE: No guidance.

[[sec_5.3]]
=== Separation of Management Activities

The SDO, if corporately linked to a certification body, quality system
registrar or similar activities, shall demonstrate a clear separation
of the management and policy-making functions of such activities from
those of standards development.

The SDO shall demonstrate compliance by reference to their policy,
organizational structure and procedural documents.

NOTE: No guidance.

[[sec_5.4]]
=== Continuity of Operations

The SDO shall:

. have a structure and available resources providing assurance on
the stability and continuity of its operations;
. have available information on its future plans regarding the development
and maintenance of standards; and
. maintain expertise for the development and the maintenance of standards.

NOTE: No guidance.

[[sec_5.5]]
=== Staff Competence

The SDO shall have sufficient and competent staff to manage its standardization
program and activities. Staff shall be knowledgeable about standardization,
including related matters of principles, policies and techniques.

NOTE: No guidance.

[[sec_5.6]]
=== Facilities

The SDO shall have appropriate facilities in Canada with sufficient
resources to meet the requirements relevant to its standards development
activities.

NOTE: No guidance.

[[sec_5.7]]
=== Record Keeping

The SDO shall prepare and maintain adequate records of its standards
development activities.

NOTE: No guidance.
